name = "PushDirectBenchmark"
uuid = "c4d38ffc-5563-45a5-b8da-8a89cabc9d44"
authors = ["Andrey Oskin"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
